[manifest]
version = "1.0.0"
priority = 0


# --------- showtime ---------

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = "if G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then"
position = "at"
payload = '''if G.GAME.used_vouchers.v_fmod_showtime and pseudorandom("showtime") > 0.8 then
    _card = {set = "Silly", area = G.pack_cards, skip_materialize = true, soulable = true, key_append = "sil1"}
elseif G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then'''
match_indent = true
times = 1

# -------- reroll superfluity --------

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase or 0
    if not skip_increment then G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase + 1 end'''
position = "at"
payload = '''if G.GAME.used_vouchers.v_fmod_reroll_superfluity and G.GAME.round_scores.times_rerolled.amt % 2 == 0 then
    G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase or 0
else
    G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase or 0
    if not skip_increment then G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase + 1 end
end'''
match_indent = true
times = 1

# -------- juggler --------

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''used_vouchers = {},'''
position = "after"
payload = '''juggler_count = 0,'''
match_indent = true
times = 1

# -------- recursive deck --------

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not next(find_joker("Showman"))) and'''
position = "at"
payload = '''elseif not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not (next(find_joker("Showman")) or G.GAME.selected_back.effect.center.key == "b_fmod_recursive")) and'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if (_type == v.type.key or _type == v.soul_set) and not (G.GAME.used_jokers[v.key] and not next(find_joker("Showman")) and not v.can_repeat_soul) and (not v.in_pool or (type(v.in_pool) ~= "function") or v:in_pool()) then'''
position = "at"
payload = '''if (_type == v.type.key or _type == v.soul_set) and not (G.GAME.used_jokers[v.key] and not (next(find_joker("Showman")) or G.GAME.selected_back.effect.center.key == "b_fmod_recursive") and not v.can_repeat_soul) and (not v.in_pool or (type(v.in_pool) ~= "function") or v:in_pool()) then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''not (G.GAME.used_jokers['c_soul'] and not next(find_joker("Showman")))'''
position = "at"
payload = '''not (G.GAME.used_jokers['c_soul'] and not (next(find_joker("Showman")) or G.GAME.selected_back.effect.center.key == "b_fmod_recursive"))'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''not (G.GAME.used_jokers['c_black_hole'] and not next(find_joker("Showman")))'''
position = "at"
payload = '''not (G.GAME.used_jokers['c_black_hole'] and not (next(find_joker("Showman")) or G.GAME.selected_back.effect.center.key == "b_fmod_recursive"))'''
match_indent = true
times = 1