[manifest]
version = "1.0.0"
priority = 0


# --------- showtime ---------

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = "if G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then"
position = "at"
payload = '''if G.GAME.used_vouchers.v_fmod_showtime and pseudorandom("showtime") > 0.8 then
    _card = {set = "Silly", area = G.pack_cards, skip_materialize = true, soulable = true, key_append = "sil1"}
elseif G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then'''
match_indent = true
times = 1
